FROM node:18.17.1-alpine


WORKDIR /app

COPY myapp/package.json ./

RUN npm install 
RUN npm install axios@1.5.1
RUN npm install react-router-dom


COPY myapp /app

RUN npm run build

EXPOSE 80

CMD tail -f /dev/null