FROM python:3.9-slim


WORKDIR /mybackend

RUN pip3 install Django==3.2
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install joblib
RUN pip3 install matplotlib
RUN pip3 install seaborn
RUN pip3 install scikit-learn==1.3.0
RUN pip3 install django djangorestframework
RUN pip3 install django-cors-headers
RUN pip3 install mysql-connector-python
RUN pip3 install pymongo
RUN pip3 install PyJWT
COPY backend/mybackend /mybackend

CMD tail -f /dev/null