name: Build-Test

run-name: ${{ github.actor }} Building and Testing

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List the contents of the repo
        run: ls -alh

      - name: Build the Docker image
        run: docker-compose build

      - name: Compose up
        run: docker-compose up -d

      - name: Testing
        run: docker-compose exec -T backend python manage.py test -v 2

  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List the contents of the repo
        run: ls -alh

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build and Push React App Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ github.workspace }}/Dockerfile.react
          push: true
          tags: pirunrat/machine_learning:${{ github.ref_name }}
          build-args: |
            VERSION=${{ github.ref_name }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ github.workspace }}/Dockerfile.django
          push: true
          tags: pirunrat/machine_learning:${{ github.ref_name }}
          build-args: |
            VERSION=${{ github.ref_name }}



      - name: Build and Push ML Model Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ github.workspace }}/Dockerfile.flask
          push: true
          tags: pirunrat/machine_learning:${{ github.ref_name }}
          build-args: |
            VERSION=${{ github.ref_name }}
